# Site settings
title: Brandon Caruana
email: brandon@caruana.me
description: > # Writer Theme is a responsive template
 My macro perspective on technology, cryptographic value creation, AI, cultural trends and the creator economy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caruana.me" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Thoughts : ['Thoughts', '/thoughts/', 'fa-blog']
  Reading : ['Reading', '/reading', 'fa-book-reader']
  Tools : ['Tools', '/tools', 'fa-tools']
  About : ['About', '/about', 'fa-user']
  ReachOut : ['Reach Out', '/contact', 'fa-id-card-alt']
single_footer: '<p>Brandon Caruana &copy; 2021 </p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Writer 2016', '/about']


# Build settings
# markdown: kramdown
plugins:
  - jekyll-feed

# Build settings
theme: minima


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
